map: map.obj
map_count: 5
output_type: glb
augmentations:
  - type: add_model
    model: cone
    scale: 5.0
    count: 10
    position: random
    color: [0, 255, 0, 255]  # Green cubes
  - type: add_model
    model: cylinder
    scale: 5.0
    count: 10
    position: random
    color: [0, 0, 255, 255]  # Blue cubes

