map_count: 3
output_type: obj
augmentations:
  - type: add_model
    model: custom
    custom_path: "./Lowpoly_tree_sample.obj"
    scale: 0.05
    count: 20
    position: random
  - type: landscape
    position: random
    count: 3
    radius: random
    smoothness: random
  - type: landscape
    position: [0, -4, 0]
    smoothness: 1
    radius: 1
    count: 1
