map: map.obj
map_count: 10
output_type: glb
augmentations:
  - type: add_model
    model: cone
    scale: 5.0
    count: 1
    position: [0,0,0]
    color: [0, 255, 0, 255]  # Green cubes
  - type: add_model
    model: cylinder
    scale: 5.0
    count: 5
    position: random
    color: [0, 0, 255, 255]  # Blue cubes
  - type: add_model
    model: custom
    custom_path: "./Lowpoly_tree_sample.obj"
    scale: 0.2
    count: 20
    position: random
  # - type:: manip_env
  #   position: random
  #   count: 10
    

